version: "3.8"

services:

  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
    container_name: "${PHP_NAME}"

  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - database
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
    container_name: "${APACHE_NAME}"

  database:
    image: mysql:${MYSQL}
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5306:3306"
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./dataTablesFix.sql:/docker-entrypoint-initdb.d/fixDump.sql
      - ./dataTablesFix.sh:/usr/src/tablefixscript/dataTablesFix.sh
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: "${MYSQL_NAME}"

networks:
  backend:
  frontend: